# Generated by Django 5.2.1 on 2025-05-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('brand', models.CharField(max_length=150, verbose_name='Nom de la marque')),
                ('purchase_date', models.DateField(verbose_name="Date d'achat")),
                ('warranty_duration_months', models.PositiveIntegerField(verbose_name='Durée de garantie (en mois)')),
                ('vendor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fournisseur')),
                ('imageReceipt', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Image du reçu')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
            ],
            options={
                'verbose_name': 'Garanties',
                'ordering': ['product_name', 'brand'],
            },
        ),
    ]
