# Generated by Django 5.2.1 on 2026-03-23 20:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0002_warranty_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warranty',
            options={'ordering': ['product_name', 'brand'], 'verbose_name': 'Garantie', 'verbose_name_plural': 'Garanties'},
        ),
        migrations.AlterField(
            model_name='warranty',
            name='brand',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nom de la marque'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='product_name',
            field=models.CharField(max_length=150, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='warranty',
            constraint=models.UniqueConstraint(fields=('user', 'product_name', 'brand'), name='unique_user_warranty'),
        ),
    ]
